//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perputakaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class pinjam
    {
        public int id { get; set; }
        public string transaksi_id { get; set; }
        public string buku_id { get; set; }
        public string user_id { get; set; }
    
        public virtual buku buku { get; set; }
        public virtual user user { get; set; }
    }
}
