//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perputakaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi
    {
        public string id { get; set; }
        public Nullable<System.DateTime> tanggal_pinjam { get; set; }
        public Nullable<System.DateTime> tanggal_kembali { get; set; }
        public Nullable<System.DateTime> tanggal_kembali_real { get; set; }
        public long terlambat { get; set; }
        public Nullable<long> denda { get; set; }
        public string status { get; set; }
    }
}
