//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perputakaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.pinjams = new HashSet<pinjam>();
        }
    
        public string id { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string telp { get; set; }
        public System.DateTime tanggal_daftar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pinjam> pinjams { get; set; }
    }
}
